version: '3'

services:
  nats:
    image: nats
    ports:
    - 4222:4222
    - 6222:6222
    - 8222:8222

  worker:
    image: nats-worker
    build:
      context: .
      dockerfile: example/Dockerfile
    environment:
      NATS_URL: nats://nats:4222
      LOG_LEVEL: DEBUG
    command: python app/worker.py

  proxy:
    image: nats-worker
    environment:
      NATS_URL: nats://nats:4222
      LOG_LEVEL: DEBUG
    command: python app/proxy.py
    ports:
    - 8888:8000
